package com.edumoca.soma.services.services;

import com.edumoca.soma.entities.GradeSectionInstitutionMap;
import com.edumoca.soma.entities.dtos.GradeSectionInstitutionMapDto;
import org.apache.poi.xssf.usermodel.XSSFSheet;

import java.util.List;
import java.util.Map;
import java.util.Set;

public interface GradeSectionInstitutionMappingService {
	GradeSectionInstitutionMapDto createGradeSectionInstitutionMapping(GradeSectionInstitutionMap gradeSectionInstitutionMap);
	GradeSectionInstitutionMapDto updateGradeSectionInstitutionMapping(GradeSectionInstitutionMap gradeSectionInstitutionMap, Integer gradeSectionInstitutionMappingId);
	List<GradeSectionInstitutionMapDto> getAllGradeSectionInstitutionMappingByInstitution(Integer institutionId);
	GradeSectionInstitutionMapDto getGradeSectionInstitutionMappingByInstitutionAndGradeSectionInstitutionMappingId(Integer institutionId, Integer gradeSectionInstitutionMappingId);
	Map<String, Set<GradeSectionInstitutionMapDto>> loadGradeSectionInstitutionMapping(XSSFSheet gradeSectionInstitutionMappingSheet, String gradeSectionInstitutionMappingSheetName);

}
