package com.edumoca.soma.services.services;

import com.edumoca.soma.entities.TeacherGradeSectionSubjectMap;
import com.edumoca.soma.entities.dtos.TeacherGradeSectionSubjectMapDto;
import org.apache.poi.xssf.usermodel.XSSFSheet;

import java.util.Map;
import java.util.Set;

public interface TeacherGradeSectionSubjectMappingService {
	TeacherGradeSectionSubjectMap createTeacherGradeSectionSubjectMapping(TeacherGradeSectionSubjectMap teacherGradeSectionSubjectMap);
	TeacherGradeSectionSubjectMap updateTeacherGradeSectionSubjectMapping(TeacherGradeSectionSubjectMap teacherGradeSectionSubjectMap);
	TeacherGradeSectionSubjectMap getTeacherGradeSectionSubjectMappingById(Integer teacherGradeSectionSubjectMappingId);
	Map<String, Set<TeacherGradeSectionSubjectMapDto>> loadTeacherGradeSectionSubjectMappings(XSSFSheet teacherGradeSectionSubjectMappingsSheet, String teacherGradeSectionSubjectMappingsSheetName);
}
